// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.example.protobuf.protocol;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.protobuf.protocol.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string phone_number = 3;</code>
     */
    java.lang.String getPhoneNumber();
    /**
     * <code>string phone_number = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();

    /**
     * <code>string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated string description = 5;</code>
     */
    java.util.List<java.lang.String>
        getDescriptionList();
    /**
     * <code>repeated string description = 5;</code>
     */
    int getDescriptionCount();
    /**
     * <code>repeated string description = 5;</code>
     */
    java.lang.String getDescription(int index);
    /**
     * <code>repeated string description = 5;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes(int index);

    /**
     * <code>.com.example.protobuf.protocol.Version version = 6;</code>
     */
    boolean hasVersion();
    /**
     * <code>.com.example.protobuf.protocol.Version version = 6;</code>
     */
    com.example.protobuf.protocol.VersionProto.Version getVersion();
    /**
     * <code>.com.example.protobuf.protocol.Version version = 6;</code>
     */
    com.example.protobuf.protocol.VersionProto.VersionOrBuilder getVersionOrBuilder();
  }
  /**
   * Protobuf type {@code com.example.protobuf.protocol.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.protobuf.protocol.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = 0;
      name_ = "";
      phoneNumber_ = "";
      email_ = "";
      description_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneNumber_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                description_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              description_.add(s);
              break;
            }
            case 50: {
              com.example.protobuf.protocol.VersionProto.Version.Builder subBuilder = null;
              if (version_ != null) {
                subBuilder = version_.toBuilder();
              }
              version_ = input.readMessage(com.example.protobuf.protocol.VersionProto.Version.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(version_);
                version_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          description_ = description_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.protocol.UserProto.internal_static_com_example_protobuf_protocol_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.protocol.UserProto.internal_static_com_example_protobuf_protocol_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.protocol.UserProto.User.class, com.example.protobuf.protocol.UserProto.User.Builder.class);
    }

    /**
     * <pre>
     *proto3.5之后，Enum类型也可以有reserved字段
     *reserved 9;
     *reserved UNKNOWN;
     * </pre>
     *
     * Protobuf enum {@code com.example.protobuf.protocol.User.Sex}
     */
    public enum Sex
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 每一个Enum都需要有一个值为0的元素，代表第一个元素 
       * </pre>
       *
       * <code>MALE = 0;</code>
       */
      MALE(0),
      /**
       * <code>FEMALE = 1;</code>
       */
      FEMALE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 每一个Enum都需要有一个值为0的元素，代表第一个元素 
       * </pre>
       *
       * <code>MALE = 0;</code>
       */
      public static final int MALE_VALUE = 0;
      /**
       * <code>FEMALE = 1;</code>
       */
      public static final int FEMALE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sex valueOf(int value) {
        return forNumber(value);
      }

      public static Sex forNumber(int value) {
        switch (value) {
          case 0: return MALE;
          case 1: return FEMALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sex> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              public Sex findValueByNumber(int number) {
                return Sex.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.example.protobuf.protocol.UserProto.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sex[] VALUES = values();

      public static Sex valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sex(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.example.protobuf.protocol.User.Sex)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_NUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object phoneNumber_;
    /**
     * <code>string phone_number = 3;</code>
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string phone_number = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList description_;
    /**
     * <code>repeated string description = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDescriptionList() {
      return description_;
    }
    /**
     * <code>repeated string description = 5;</code>
     */
    public int getDescriptionCount() {
      return description_.size();
    }
    /**
     * <code>repeated string description = 5;</code>
     */
    public java.lang.String getDescription(int index) {
      return description_.get(index);
    }
    /**
     * <code>repeated string description = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes(int index) {
      return description_.getByteString(index);
    }

    public static final int VERSION_FIELD_NUMBER = 6;
    private com.example.protobuf.protocol.VersionProto.Version version_;
    /**
     * <code>.com.example.protobuf.protocol.Version version = 6;</code>
     */
    public boolean hasVersion() {
      return version_ != null;
    }
    /**
     * <code>.com.example.protobuf.protocol.Version version = 6;</code>
     */
    public com.example.protobuf.protocol.VersionProto.Version getVersion() {
      return version_ == null ? com.example.protobuf.protocol.VersionProto.Version.getDefaultInstance() : version_;
    }
    /**
     * <code>.com.example.protobuf.protocol.Version version = 6;</code>
     */
    public com.example.protobuf.protocol.VersionProto.VersionOrBuilder getVersionOrBuilder() {
      return getVersion();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phoneNumber_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      for (int i = 0; i < description_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_.getRaw(i));
      }
      if (version_ != null) {
        output.writeMessage(6, getVersion());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phoneNumber_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < description_.size(); i++) {
          dataSize += computeStringSizeNoTag(description_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDescriptionList().size();
      }
      if (version_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getVersion());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.protocol.UserProto.User)) {
        return super.equals(obj);
      }
      com.example.protobuf.protocol.UserProto.User other = (com.example.protobuf.protocol.UserProto.User) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getPhoneNumber()
          .equals(other.getPhoneNumber());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getDescriptionList()
          .equals(other.getDescriptionList());
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && getVersion()
            .equals(other.getVersion());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PHONE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getDescriptionCount() > 0) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescriptionList().hashCode();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.protocol.UserProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.protocol.UserProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.protocol.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.protocol.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.protocol.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.protocol.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.protocol.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.protocol.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.protocol.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.protobuf.protocol.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.protocol.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.protocol.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.protocol.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.protobuf.protocol.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.protobuf.protocol.User)
        com.example.protobuf.protocol.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.protocol.UserProto.internal_static_com_example_protobuf_protocol_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.protocol.UserProto.internal_static_com_example_protobuf_protocol_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.protocol.UserProto.User.class, com.example.protobuf.protocol.UserProto.User.Builder.class);
      }

      // Construct using com.example.protobuf.protocol.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        phoneNumber_ = "";

        email_ = "";

        description_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (versionBuilder_ == null) {
          version_ = null;
        } else {
          version_ = null;
          versionBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.protocol.UserProto.internal_static_com_example_protobuf_protocol_User_descriptor;
      }

      public com.example.protobuf.protocol.UserProto.User getDefaultInstanceForType() {
        return com.example.protobuf.protocol.UserProto.User.getDefaultInstance();
      }

      public com.example.protobuf.protocol.UserProto.User build() {
        com.example.protobuf.protocol.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.protobuf.protocol.UserProto.User buildPartial() {
        com.example.protobuf.protocol.UserProto.User result = new com.example.protobuf.protocol.UserProto.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.phoneNumber_ = phoneNumber_;
        result.email_ = email_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          description_ = description_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.description_ = description_;
        if (versionBuilder_ == null) {
          result.version_ = version_;
        } else {
          result.version_ = versionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.protocol.UserProto.User) {
          return mergeFrom((com.example.protobuf.protocol.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.protocol.UserProto.User other) {
        if (other == com.example.protobuf.protocol.UserProto.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPhoneNumber().isEmpty()) {
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.description_.isEmpty()) {
          if (description_.isEmpty()) {
            description_ = other.description_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDescriptionIsMutable();
            description_.addAll(other.description_);
          }
          onChanged();
        }
        if (other.hasVersion()) {
          mergeVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.protobuf.protocol.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.protobuf.protocol.UserProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneNumber_ = "";
      /**
       * <code>string phone_number = 3;</code>
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone_number = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone_number = 3;</code>
       */
      public Builder setPhoneNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone_number = 3;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string phone_number = 3;</code>
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList description_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDescriptionIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          description_ = new com.google.protobuf.LazyStringArrayList(description_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string description = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDescriptionList() {
        return description_.getUnmodifiableView();
      }
      /**
       * <code>repeated string description = 5;</code>
       */
      public int getDescriptionCount() {
        return description_.size();
      }
      /**
       * <code>repeated string description = 5;</code>
       */
      public java.lang.String getDescription(int index) {
        return description_.get(index);
      }
      /**
       * <code>repeated string description = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes(int index) {
        return description_.getByteString(index);
      }
      /**
       * <code>repeated string description = 5;</code>
       */
      public Builder setDescription(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDescriptionIsMutable();
        description_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string description = 5;</code>
       */
      public Builder addDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDescriptionIsMutable();
        description_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string description = 5;</code>
       */
      public Builder addAllDescription(
          java.lang.Iterable<java.lang.String> values) {
        ensureDescriptionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, description_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string description = 5;</code>
       */
      public Builder clearDescription() {
        description_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string description = 5;</code>
       */
      public Builder addDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDescriptionIsMutable();
        description_.add(value);
        onChanged();
        return this;
      }

      private com.example.protobuf.protocol.VersionProto.Version version_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.protobuf.protocol.VersionProto.Version, com.example.protobuf.protocol.VersionProto.Version.Builder, com.example.protobuf.protocol.VersionProto.VersionOrBuilder> versionBuilder_;
      /**
       * <code>.com.example.protobuf.protocol.Version version = 6;</code>
       */
      public boolean hasVersion() {
        return versionBuilder_ != null || version_ != null;
      }
      /**
       * <code>.com.example.protobuf.protocol.Version version = 6;</code>
       */
      public com.example.protobuf.protocol.VersionProto.Version getVersion() {
        if (versionBuilder_ == null) {
          return version_ == null ? com.example.protobuf.protocol.VersionProto.Version.getDefaultInstance() : version_;
        } else {
          return versionBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.example.protobuf.protocol.Version version = 6;</code>
       */
      public Builder setVersion(com.example.protobuf.protocol.VersionProto.Version value) {
        if (versionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          version_ = value;
          onChanged();
        } else {
          versionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.example.protobuf.protocol.Version version = 6;</code>
       */
      public Builder setVersion(
          com.example.protobuf.protocol.VersionProto.Version.Builder builderForValue) {
        if (versionBuilder_ == null) {
          version_ = builderForValue.build();
          onChanged();
        } else {
          versionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.example.protobuf.protocol.Version version = 6;</code>
       */
      public Builder mergeVersion(com.example.protobuf.protocol.VersionProto.Version value) {
        if (versionBuilder_ == null) {
          if (version_ != null) {
            version_ =
              com.example.protobuf.protocol.VersionProto.Version.newBuilder(version_).mergeFrom(value).buildPartial();
          } else {
            version_ = value;
          }
          onChanged();
        } else {
          versionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.example.protobuf.protocol.Version version = 6;</code>
       */
      public Builder clearVersion() {
        if (versionBuilder_ == null) {
          version_ = null;
          onChanged();
        } else {
          version_ = null;
          versionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.example.protobuf.protocol.Version version = 6;</code>
       */
      public com.example.protobuf.protocol.VersionProto.Version.Builder getVersionBuilder() {
        
        onChanged();
        return getVersionFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.example.protobuf.protocol.Version version = 6;</code>
       */
      public com.example.protobuf.protocol.VersionProto.VersionOrBuilder getVersionOrBuilder() {
        if (versionBuilder_ != null) {
          return versionBuilder_.getMessageOrBuilder();
        } else {
          return version_ == null ?
              com.example.protobuf.protocol.VersionProto.Version.getDefaultInstance() : version_;
        }
      }
      /**
       * <code>.com.example.protobuf.protocol.Version version = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.protobuf.protocol.VersionProto.Version, com.example.protobuf.protocol.VersionProto.Version.Builder, com.example.protobuf.protocol.VersionProto.VersionOrBuilder> 
          getVersionFieldBuilder() {
        if (versionBuilder_ == null) {
          versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.protobuf.protocol.VersionProto.Version, com.example.protobuf.protocol.VersionProto.Version.Builder, com.example.protobuf.protocol.VersionProto.VersionOrBuilder>(
                  getVersion(),
                  getParentForChildren(),
                  isClean());
          version_ = null;
        }
        return versionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.protobuf.protocol.User)
    }

    // @@protoc_insertion_point(class_scope:com.example.protobuf.protocol.User)
    private static final com.example.protobuf.protocol.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.protocol.UserProto.User();
    }

    public static com.example.protobuf.protocol.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.example.protobuf.protocol.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_protobuf_protocol_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_protobuf_protocol_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\035com.example.protobuf.proto" +
      "col\032\016imported.proto\"\266\001\n\004User\022\n\n\002id\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\022\024\n\014phone_number\030\003 \001(\t\022\r\n\005" +
      "email\030\004 \001(\t\022\023\n\013description\030\005 \003(\t\0227\n\007vers" +
      "ion\030\006 \001(\0132&.com.example.protobuf.protoco" +
      "l.Version\"\033\n\003Sex\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001J\004" +
      "\010\t\020\nB\013B\tUserProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.protobuf.protocol.Imported.getDescriptor(),
        }, assigner);
    internal_static_com_example_protobuf_protocol_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_protobuf_protocol_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_protobuf_protocol_User_descriptor,
        new java.lang.String[] { "Id", "Name", "PhoneNumber", "Email", "Description", "Version", });
    com.example.protobuf.protocol.Imported.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
